version: '3.1'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${WSRS_MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${WSRS_MYSQL_ROOT_PASSWORD}
    volumes:
      - phpmyadmin:/var/lib/phpmyadmin

volumes:
  db:
    driver: local
  phpmyadmin:
    driver: local